[newrelic]
# license_key will be read from NEW_RELIC_LICENSE_KEY environment variable
app_name = TaskUno Email Service
monitor_mode = true
log_file = /tmp/newrelic-python-agent.log
log_level = info

[newrelic:feature_flag]
application_logging.enabled = true
application_logging.forwarding.enabled = true
application_logging.metrics.enabled = true
application_logging.local_decorating.enabled = true
